# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Hello
tagline:          "It's just me"
description:      'Welcome, read about my life and what intrests me'
url:              http://blog.wubsinfo.nl
baseurl:          /

author:
  name:           'Bram Wubs'
  url:            https://twitter.com/bwubs

paginate:         4

# Custom vars
version:          2.1.0

github: https://github.com/megawubs
